### ISSUE TITLE
Not able to run the tool against a .NET 9 project

### ISSUE THREAD

**Issue by danielcrenna** [Dreamescaper/GenerateAspNetCoreClient#31]
When running the tool against .NET 9, there are missing types that occur due to the ASP.NET Core Web API using types exclusive to .NET 9. 

Upgrading to .NET 9 in a fork works fine, though I suspect you'd want to think about this before asking installers to have .NET 9 installed.

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'System.TimeSpan System.TimeSpan.FromSeconds(Int64)'.
   at Microsoft.AspNetCore.Hosting.WebHostOptions..ctor(IConfiguration primaryConfiguration, IConfiguration fallbackConfiguration, IHostEnvironment environment)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ExecuteHostingStartups()
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<.ctor>b__4_0(IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.InitializeHosting(BootstrapHostBuilder bootstrapHostBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in Program.cs:line 4
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   ```

**Comment by Dreamescaper** [comment]
Yeah, unfortunatelly, I don't know, how to support NET9 _and_ avoid requiring to install NET9. 
Thanks for raising it!

**Comment by Jappinen** [comment]
Yeah I too ran into this and had to build my own version, code changes were thankfully minimal but I'll have to think something for the rest of the team at some point.

Is there some problem requiring the NET9 for tool users (assuming the older projects still work, haven't tested that myself)? I mean, isn't that how it currently is that NET8 is required for projects using 6 and 7?

**Comment by Dreamescaper** [comment]
No, not really a problem. I plan to update it shortly. Apart from simply to update it to net9.0, I want to update tests to verify both net8.0 and net9.0.
